default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: the_life_planner_development
  cache:
    <<: *sqlite
    database: solid/the_life_planner_development_cache.sqlite3
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: the_life_planner_production
    username: the_life_planner
    password: <%= ENV["THE_LIFE_PLANNER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: the_life_planner_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: the_life_planner_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: the_life_planner_production_cable
    migrations_paths: db/cable_migrate
